# Generated by Django 4.0 on 2021-12-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dueDate',
            new_name='due_date',
        ),
    ]
